import jsPDF from 'jspdf';
import { DB, A4_W, A4_H, MARGIN } from '../constants';

/**
 * Draws a professional two-zone footer on every page.
 *
 * Zone 1 (light strip, 6 mm): system-generated metadata notice.
 * Zone 2 (blue bar, 8 mm): tagline left + page counter right.
 */
export function drawSharedFooters(
  doc: jsPDF,
  totalPages: number,
  docType: 'COA' | 'QT' = 'COA',
  docVersion: string = 'Rev.1'
): void {
  const NOTICE_H = 5.5;   // height of the metadata strip
  const BAR_H    = 8;     // height of the blue bar
  const NOTICE_Y = A4_H - NOTICE_H - BAR_H;
  const BAR_Y    = A4_H - BAR_H;

  const now   = new Date();
  const stamp = now.toLocaleString('en-ZM', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: false,
    timeZone: 'Africa/Lusaka',
  });

  const longDocType = docType === 'COA'
    ? 'Certificate of Analysis'
    : 'Service Quotation';

  for (let pg = 1; pg <= totalPages; pg++) {
    doc.setPage(pg);

    // ── Metadata strip (white background) ──────────────────────────────
    doc.setFillColor(248, 250, 253); // near-white tint
    doc.rect(0, NOTICE_Y, A4_W, NOTICE_H, 'F');

    // Top hairline rule
    doc.setDrawColor(200, 218, 240);
    doc.setLineWidth(0.25);
    doc.line(MARGIN, NOTICE_Y, A4_W - MARGIN, NOTICE_Y);

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(6.5);
    doc.setTextColor(130, 130, 130);

    const noticeText =
      `This ${longDocType} was electronically generated by the NWSC Laboratory Information System.  ` +
      `${docVersion}  |  Generated: ${stamp} CAT`;
    doc.text(noticeText, MARGIN, NOTICE_Y + 3.8, { maxWidth: A4_W - 2 * MARGIN });

    // ── Blue bar ───────────────────────────────────────────────────────
    doc.setFillColor(...DB);
    doc.rect(0, BAR_Y, A4_W, BAR_H, 'F');

    // Tagline (Left)
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text('Bigger, Better, Smarter', MARGIN, BAR_Y + 5.2);

    // NWSC centre stamp
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(180, 210, 240);
    doc.text('NWSC SHEQ · nwsc.com.zm', A4_W / 2, BAR_Y + 5.2, { align: 'center' });

    // Page counter (Right)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text(`Page ${pg} of ${totalPages}`, A4_W - MARGIN, BAR_Y + 5.2, { align: 'right' });
  }
}
